name: Build, Test, and Lint
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    container: huskysat/lost:latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: 🛠 Build
      run: CXXFLAGS=-Werror make -j$(($(nproc)+1))
    - name: 📊 Unit Tests
      run: CXXFLAGS=-Werror make test -j$(($(nproc)+1))
    - run: pip install cpplint
    - name: Lint
      run: cpplint --recursive src/ test/
    - name: Line Endings
      uses: erclu/check-crlf@v1
